### ISSUE TITLE
Make Quantizer pitch classes go bottom to top

### ISSUE THREAD

**Issue by Letheward** [VCVRack/Fundamental#124]
![confusion](https://user-images.githubusercontent.com/59071629/118906696-d8c14880-b950-11eb-8251-2048413a2026.png)
As the picture showed, Quantizer pitch classes go from *top to bottom*, but Octave module is *bottom to top*.

This is not very consistent, and also not intuitive because typically people think higher in visual represent higher pitch.  
I personally misinterpret the ordering for days, because my first use of Quantizer is in a drone patch.

I would like it to change to bottom to top, also a description in manual will help if people are confused about the new ordering.

**Comment by MarcBoule** [comment]
For the quantizer, I would guess that it was made like that in order to be consistent with how most Eurorack quantizers are setup. Except for the TipTop one, all the other ones I have seen that are vertical are like that (C at the top, B at the bottom): µScale, Penrose, ADDAC207, etc...

https://www.modulargrid.net/e/modules/browser?SearchName=&SearchVendor=&SearchFunction=35&SearchSecondaryfunction=&SearchHeight=&SearchTe=&SearchTemethod=max&SearchBuildtype=&SearchLifecycle=&SearchSet=&SearchMarketplace=&SearchIsmodeled=0&SearchShowothers=0&order=tag&direction=asc

**Comment by Letheward** [comment]
> I would guess that it was made like that in order to be consistent with how most Eurorack quantizers are setup. 

If that's the case it does make sense, but still a bit annoying. Then the problem will be the description in manual, which is still in TODO state as of now.
