### ISSUE TITLE
Fundamental v0.6 Delay module - no delay signal

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/Fundamental#35]
Hi, just found out that Fundamental Delay module has an issue:
There's no delayed signal coming out of it, color and mix knobs work ok, but the delay part does nothing. 
Note: (as a couple of AS modules are based on Fundamental Delay, both suffer the same issue).

Thanks!

**Comment by PawelHadrian** [comment]
Any news on this issue?

**Comment by AndrewBelt** [comment]
No

**Comment by ndrspcfd** [comment]
Delay is working for me with current master Fundamental against current master Rack, I think because the underlying issue of a missing suitable samplerate conversion is now dealt with after 88d5cc0 and its pals. Personally I'm very pleased to see this back and I hope the delay dependent AS modules can take advantage. 

Another approach, which I had used to implement a primitive replacement module for Fundamental's Delay while we were waiting, is to use a [delay-line instance from ccrma's liberally licensed STK](https://github.com/thestk/stk/blob/master/src/DelayA.cpp) which is very flexible, and produces quite acceptable sounding fractional delay (to my ear) without a need for samplerate shenans.

**Comment by AScustomWorks** [comment]
@ndrspcfd Hi, and thanks for the heads up!, do you have an example with your implementation of STK? I haven't looked into it yet ;)
