### ISSUE TITLE
grayscale algorytm misses first step 

### ISSUE THREAD

**Issue by gentleclockdivider** [VCVRack/Fundamental#53]
I didn't find grayscale under the directories here , so I post this under Fundamental .
Issue
Sometimes the first step is ommitted  , this happens with all sequencers in vcv rack 
-Route a gate from  'midi 1' out to state in of grayscale , no looping mode or press start with the mouse 
-square lfo as clock .
-enable step 1/3/5 of  grayscale , and assign pattern out to a sound source .

I even went further and send a gate from 'midi 1' to reset in of the square lfo .
It's a bit hit and miss ..but it happens with a lot of sequencer s in vcv rack .
This could be lfo related , where a high pulse is missed from the start .
If so , vcv could benefit from an accurate master clock

**Comment by MarcBoule** [comment]
We had a somewhat related discussions regarding a part of this topic over here, in case you would like to read more: https://github.com/VCVRack/Rack/issues/938

**Comment by AndrewBelt** [comment]
You're right, this is a duplicate.

**Comment by MarcBoule** [comment]
Well, if we use the onboard clock in SEQ-3, then there is no problem. But with an external clock that has its reset input (aka sync for LFOs) wired to a global reset, and with SEQ-3's reset also wired to this global reset, as shown in the following setup, then there is a problem:
![image](https://user-images.githubusercontent.com/33604154/43100885-b83d1b64-8e94-11e8-9b8b-706089388f04.png)
In this use case, when the seq is running and it is not on the first step, and pressing the Momentay switch on AS to perform a patch-wide reset, SEQ-3 will always restart on the *second* step. This is what prompted my whole discussion thread, since my sequencers were doing the same thing. When I figured that I should simply ignore any clock events during the 1st milisecond after receving a reset, which solved the problem in my case, I wanted to share this and was hoping that others would think about such issues. I found it unreasonable to accept a clock event so close to a reset, and I adopted the strategy of declaring this a parasitic clock event given routing delays though modules. Not saying I have the perfect solution and that other seqs should do the same, but just wanted to shine some light on this topic.

One could also argue that it is up to the user to be aware of routing delays through modules, and in my above use case, if we simply route the reset signal through a dummy module, then everything works perfectly:
![image](https://user-images.githubusercontent.com/33604154/43101351-2d8e114c-8e96-11e8-808b-e017c6a4e4c8.png)
I just think that since the fix I proposed is quite simple, and especially if it avoids users saying that our seqs are not working properly, then in my case implementing the 1ms clock ignore is a no-brainer! :-)

**Comment by AndrewBelt** [comment]
You should post that in the other thread. It's very low in my priority list right now so I haven't read any of the posts.

**Comment by MarcBoule** [comment]
Will do. 
I also had thoughts about the Sequential Switch issue that was raised in https://github.com/VCVRack/Fundamental/issues/52
which has some similarities, but would require a slightly different approach IMO. We could think of delaying the IN-OUT signal path by an additional sample, such that switching the inputs could be done internally at the same time as the clock edge is detected. When SS came out a while back, I had struggled with this, and I have always thought that a clock should be easilty dividable using a SS, but as stated in the issue 52 (which echos my experience with SS-x), we need to mess with signal delays ouselves to make it work flawlessly. 

Just sharing thoughts on these topics, and indeed, I can understand that it would be low priority. Cheers!
